image: node:18.19.1                                                                                                 

pipelines:
  default:
    - step:
        name: Install Dependencies
        caches:
          - node 
        script:
          - npm install 

    - step:
        name: Run Tests
        script:
          - npm test 

    - step:
        name: Build
        script:
          - npm run build